
server:
  port: 9004
dubbo:
  application:
    # 服务名称，保持唯一
    name: server-consumer-evan
    # zookeeper地址，用于向其注册服务
  registry:
    protocal: zookeeper
    address: zookeeper://127.0.0.1:2181
  protocol:
    name: dubbo
    port: 20880
  scan:
    base-packages: com.evan.consumer